# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

testCpp_permutation <- function(x, B = 1e5L) {
    .Call(`_sigtestscpp_testCpp_permutation`, x, B)
}

testCpp_bootstrap <- function(x, B = 1e5L) {
    .Call(`_sigtestscpp_testCpp_bootstrap`, x, B)
}

